# Generated by Django 6.0.3 on 2026-03-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_latitude_booking_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pickup_scheduled', 'Pickup Scheduled'), ('picked_up', 'Vehicle Picked Up'), ('washing', 'Washing In Progress'), ('coating', 'Ceramic Coating'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
