# Generated by Django 6.0.3 on 2026-03-07 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_status'),
        ('services', '0002_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='services.timeslot'),
            preserve_default=False,
        ),
    ]
