# Generated by Django 6.0.3 on 2026-03-30 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_remove_booking_service_booking_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(choices=[('VIP', 'VIP'), ('Zone A', 'Zone A'), ('Zone B', 'Zone B'), ('Zone C', 'Zone C')], max_length=20)),
                ('slot_number', models.CharField(max_length=10, unique=True)),
                ('floor', models.IntegerField(default=0)),
                ('price_per_hour', models.DecimalField(decimal_places=2, default=99, max_digits=8)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='parking_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.parkingslot'),
        ),
    ]
