# Generated by Django 6.0.3 on 2026-03-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Awaiting Approval'), ('confirmed', 'Confirmed'), ('queued', 'In Queue'), ('pre_wash', 'Pre-Wash Inspection'), ('washing', 'Deep Cleaning'), ('detailing', 'Precision Detailing'), ('waxing', 'Wax & Polish'), ('inspection_final', 'Final Quality Check'), ('ready', 'Ready for Handover'), ('completed', 'Service Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
